# Generated by Django 3.2.15 on 2022-09-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_rename_gigs_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
