# Generated by Django 3.2.15 on 2022-09-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0009_alter_gigreview_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigreview',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='gigreview',
            name='item',
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
        migrations.DeleteModel(
            name='GigReview',
        ),
    ]
