# Generated by Django 3.2.15 on 2022-09-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_gig_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigreviews', to='watchlist_app.gig'),
        ),
    ]
