# Generated by Django 3.2.15 on 2022-09-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0011_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
